axis_linear: 1
scale_linear: 0.8
scale_linear_turbo: 1.2

axis_angular: 0
scale_angular: 1.5
scale_angular_turbo: 2.0

enable_button: 6  # L2 shoulder button
enable_turbo_button: 7  # L1 shoulder button